FROM rayproject/ray:2.10.0-py311

WORKDIR /app

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.processor.txt .
RUN pip install --no-cache-dir -r requirements.processor.txt

COPY processor/ processor/
RUN cd processor/v3_cython && python setup.py build_ext --inplace

ENV PYTHONPATH=/app
